### ISSUE TITLE
Template Source Changes

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#1399]
Can we specify a template source in either a entry or layer. Where you can specify the provider in the template source. This will make it easier to ship shared templates and elements into different workspaces without having to add additional templates and elements into templates. This can also further clean up the template object on massive workspaces that use a lot of shared templates.

This will also want to have the ability where if you specify a template in the template object it will override the template specified on the layer/entry. (This is open for discussion)

**Comment by dbauszus-glx** [comment]
A template should never be defined by a client without restrictions.

Let's say there is a template to query locations.

The src is omitted in the workspace.template entry.

The src is provided by the query request.

The template is loaded by the getTemplates module provided to the query module and executed.

Now, anybody with a valid token could form a request providing a src of choice which loads a harmful query template or worse module.

The only way this could work is by restricting the source which would be incredibly convoluted.

Much easier would be to control the cache. For example file: should never be cached. I change the file and the next time I request the template it is read from the file which is almost immediate.

A second step could then be to introduce a flag which controls whether a template should be cached.

Let's say the template is on cloudfront, or any cdn really, and I have access to the cdn. Then I can change the template and the next request would reload the changed template prior to executing since the template is never cached.
