### ISSUE TITLE
applyFilter layer reload method

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1520]
It is currently not easily possible to alter the applyFilter method in mapp.ui.layers.filters or apply custom methods to the layer.reload event method.

**Comment by RobAndrewHurst** [comment]
It should be possible to alter the applyFilter method. In order to do so the applyFilter method will be added to the filterMethods object exported from ui/layers/filter module.

The applyFilter debounces the layer.reload()

The vector and mvt layer.reload() methods now support a callback argument. This allows the applyFilter method to provide the reloadCallback method which renders the style.legend. This callback should only be executed when the reload is called from the applyFilter method, not on every reload of the layer, eg. when the layer.show method is called.
