### ISSUE TITLE
layer filter panel and clearAll method

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1528]
The /ui/layer/panels/filter module is currently undocumented.

The dropdown has complex callback method with nested methods.

The nested methods to remove a filter [card] must moved to the ui/layers/filter[Methods] module.

Instead of calling the layer.reload / dispatch the changeend on the mapview. The applyFilter method should be called after filters are removed. This should be part of the remove method which will ensure the applyFilter is debounced.

**Comment by dbauszus-glx** [comment]
https://github.com/GEOLYTIX/xyz/pull/1525 must should be merged first.

**Comment by RobAndrewHurst** [comment]
- The card element and filter panel module and method have now been documented.

- Checks for types have been added.

- The removeFilter method has been added to the layer filters module. The removeFilter calls the apply filter method rather than duplicating code from the apply filter method.

- Elements are assigned to the layer filter object rather than const within the panel method.

- The dropdown callback method has been reduced in complexity.

- The `dropdown` elements did not have a string value if there was no `title` on the `entry`. It now uses `title`, then `label` then `field`.

```js
const li = mapp.utils.html.node`<li
      data-value=${entry.option}
      onclick=${(e) => params.liOnClick(e, entry)}>
      ${entry.title || entry.label || entry.field}`
```
