### ISSUE TITLE
version check util

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1554]
There should be a version check utility method which returns true if a the current mapp version is equal or higher a float of `major.minor`

**Comment by simon-leech** [comment]
**Changes Applied**
Utility function for checking the current `mapp.version` against a provided value. 
The provided value is a string such as  '4.8.0'.
The utility splits the provided value and the mapp version into major and minor versions, and compares them separately. 
The logic is as follows: 
- If the major version is more than or equal to the given value, return true.
- If the major version numbers are equal, it will compare the minor version numbers.
- If the minor version numbers are equal, it will compare the patch version numbers.
- Otherwise, return false.

I have also provided tests that are currently passing.
