### ISSUE TITLE
zero env config fails in acl module.

### ISSUE THREAD

**Issue by dbauszus-glx** [GEOLYTIX/xyz#1687]
Without PRIVATE or PUBLIC env the connection will be undefined and fail to look for the first array entry.

```js
const connection = process.env.PRIVATE?.split('|') || process.env.PUBLIC?.split('|')

const acl_table = connection[1]?.split('.').pop()
```

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Fix the issue where undefined connection causes errors when accessing connection[1]. Implement early return if connection is undefined.

I also created pull request: https://github.com/GEOLYTIX/xyz/pull/1688


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
