### ISSUE TITLE
Overspilling Editable Dropdown

### ISSUE THREAD

**Issue by simon-leech** [GEOLYTIX/xyz#1772]
## Description

An editable dropdown wraps as seen below
![image](https://github.com/user-attachments/assets/0b4c90f7-a799-40bd-8774-c6b53fc0334c)

When you save this however, it saves and does not wrap so overspills
![image](https://github.com/user-attachments/assets/4ead1cfd-4655-4eaa-9458-27ee35bb1d58)

## Type of Issue 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug

**Comment by dbauszus-glx** [comment]
The ellipsis should be shown like when the input (dropdown button) is on it's own line.

![image](https://github.com/user-attachments/assets/2e016f98-77ba-40e2-919c-2911d3970b44)

The text (header) should not wrap. This is possible but will create all sorts of layout madness with complex element groups such as tables.

This is specifically set to no-wrap. Like a text input cannot wrap.

![image](https://github.com/user-attachments/assets/a5c2040f-a749-4e31-a694-59a2ff542bda)

The issue is not with wrapping but layout of the dropdown element group. This div should not expand beyond the grid column.

![image](https://github.com/user-attachments/assets/94ea4783-92e7-4051-8321-1c13f1872ca1)

**Comment by dbauszus-glx** [comment]
https://stackoverflow.com/questions/43311943/prevent-content-from-expanding-grid-items

![image](https://github.com/user-attachments/assets/cc92cd33-f36f-46ee-9cc6-8657223d6c5b)
