### ISSUE TITLE
Support for TomTom isoline API

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#354]
also add it to docs.

**Comment by dbauszus-glx** [comment]
I changed the tomtom method to use a proxy request instead of the provider/tomtom.

This may not work if tomtom keys are tied to a request domain like the mapbox api. In this case the key would have to be provided in the parameter object and the request would have to be done directly like the mapbox isochrone requests.

**Comment by cityremade** [comment]
Request fixed, added to docs.

**Comment by cityremade** [comment]
https://geolytix.github.io/xyz/docs/workspace/locations/geometry/
