### ISSUE TITLE
Dataviews - no data returned 

### ISSUE THREAD

**Issue by cityremade** [GEOLYTIX/xyz#448]
At the moment when no data is returned from a chart/table we get text from dictionary No data available.
Can this be made scriptable? Sometimes custom message might be needed.

**Comment by cityremade** [comment]
<img width="826" alt="Screenshot 2022-01-06 at 15 57 56" src="https://user-images.githubusercontent.com/7070711/148402537-902d8be0-2352-49ef-a481-cf329d23455b.png">

**Comment by dbauszus-glx** [comment]
Absolutely.

Whereas previously the responseFunction was checked for an executed within either the setData method of charts and tables, this has now been moved into the dataview update method.

```js
const response = await mapp.utils.xhr(`${_this.host}/api/query?`+paramString)

if (typeof _this.responseFunction === 'function') return _this.responseFunction(response);
    
_this.setData(response)
```

By not calling _this.setData() in the response function when no data is there to be processed you can override the default no data behaviour. It is imperative to return the responseFunction and not call the setData after directly after the responseFunction in order to allow for async execution within the responseFunction execution.

I still need to check the default behaviour for no data charts with a test case.
