### ISSUE TITLE
Chart Selection Bug

### ISSUE THREAD

**Issue by RobAndrewHurst** [GEOLYTIX/xyz#88]
Charts on a location, are not deselecting after unchecking the checkbox.

**Comment by RobAndrewHurst** [comment]
![peek 2019-03-07 16-49](https://user-images.githubusercontent.com/43169158/53965063-2ac37e00-40f9-11e9-8e98-014e22cc1c2e.gif)

**Comment by dbauszus-glx** [comment]
Fixed in [development branch](https://github.com/GEOLYTIX/xyz/commit/0eaa21d7d94c9d17dcb0067f49537f353cdc9981)


Anything location view should **not** be created in tableview/locationTable.mjs

I added a callback as second input to this module.

The callback will be called with the table data.
```
    xhr.onload = e => {

      if (e.target.status !== 200) return;

      table.Tabulator.setData(e.target.response);

      table.Tabulator.redraw(true);

      if (callback) callback(e.target.response);

    };
```

In location/view/tableDefinition.mjs the tableChart function is passed to the locationTable as callback.

```
  function showTab() {

    entry.location.tables.push(entry);

    entry.target = _xyz.tableview.node.querySelector('.table');

    _xyz.tableview.locationTable(entry, tableChart);

  }
```

A row with the chart node will be added after the tableview entry when a chart is defined on the table view.

```
  if (entry.chart) {

    const tr = _xyz.utils.hyperHTML.wire()`<tr class="table-chart">`;  
    const td = _xyz.utils.hyperHTML.wire()`<td colspan=2>`;
    tr.appendChild(td);

    entry.chart.node = _xyz.utils.hyperHTML.wire()`<div class="table-section">`;
    td.appendChild(entry.chart.node);

    entry.location.view.node.appendChild(tr);

  }
```

This will be emptied in the onchange event when the tickbox is removed.

```
      if (entry.display) {
        showTab();
      } else {
        _xyz.tableview.removeTab(entry);
        if (entry.chart) entry.chart.node.innerHTML = '';
      }
```

The tableChart method itself is really simple.

Instead of pushing fields into a new array I use map on the data array to map the fields to the fields array.

I also use fields.some() to check whether any of the fields have a displayValue to prevent drawing an empty chart.

Thereafter I just put the chart into entry.chart.now.

```
  function tableChart(data) {

    if (!entry.chart) return;

    const fields = data.map(field => ({
      label: field.rows,
      field: entry.chart.field,
      value: field[entry.chart.field],
      displayValue: field[entry.chart.field]
    }));

    if (fields.length && fields.some(field => field.displayValue)) {
       
      entry.chart.node.appendChild(_xyz.utils.chart({
        label: entry.title,
        fields: fields,
        chart: entry.chart
      }));

    }

  }
```

**Comment by dbauszus-glx** [comment]
I disabled the header for the time being as it is the same as the table entry.

**Comment by RobAndrewHurst** [comment]
Getting another bit of odd behaviour, chart duplication occurs after deselecting one chart, the other curret chart duplicates itself.

**Comment by RobAndrewHurst** [comment]
![peek 2019-03-08 09-00](https://user-images.githubusercontent.com/43169158/54013241-0e6b2400-4181-11e9-8bdb-44a3c465d5c5.gif)

**Comment by dbauszus-glx** [comment]
Bit of a tricky one this. When a table get's removed the next table is activated and will fire again the callback. I added that the chart is rebuild when the callback is fired instead of just creating a new chart.

However. the chart wasn't possible on reports since the tables where created manually and not from the location view meaning there was no data to be passed back in callback.

I added a target_id to the tabledefinition. If no tableview control is present the table will be created inside the the target_id element.

This makes reports simpler as well as I just need to define the target_id for the table elements on the report and don't have to hardcode the location tables in the report script. Although that should work as well.

Tables can now be toggled on reports and the charts should show reports.

https://github.com/GEOLYTIX/xyz/commit/05de055ab03f8ba72375ef2b56ee54b275ef7771
